# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic
        user: root
    environment:
      PYTHON_VERSION: 3.7.1
    steps:
      - checkout:
          path: /root/project/src
      - run:
          name: Setup Miniconda
          command: |
            apt update
            apt install -y wget
            apt-get update --yes && apt-get upgrade --yes
            apt-get install g++ --yes
            cd $HOME
            wget "https://repo.anaconda.com/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh" -O miniconda.sh
            printf '%s' "8a324adcc9eaf1c09e22a992bb6234d91a94146840ee6b11c114ecadafc68121  miniconda.sh" | sha256sum -c
            bash miniconda.sh -b -p $HOME/miniconda
      - run:
          name: Setup environment and run tests
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source $HOME/miniconda/etc/profile.d/conda.sh
            conda update -y conda
            cd /root/project/src 
            conda env create -f environment.yml
            conda activate fringe 
            conda install gxx_linux-64
            conda install -c anaconda make 
            echo $CXX
            python --version
            python -c "import numpy; print(numpy.__version__)"
      - run:
          name: Install ISCE and test ISCE
          command: |
            source $HOME/miniconda/etc/profile.d/conda.sh
            conda activate fringe
            export PATH="$ISCE_HOME/bin:$ISCE_HOME/applications:$PATH"
      - run:
          name: Install Fringe and test Fringe
          command: |
            source $HOME/miniconda/etc/profile.d/conda.sh
            conda activate fringe
            export PATH="$ISCE_HOME/bin:$ISCE_HOME/applications:$PATH"
            cd /root/project/
            mkdir install build
            cd build
            cmake -DCMAKE_INSTALL_PREFIX=../install ../src
            make all
            make install
            export PYTHONPATH=$PYTHONPATH:~/install/python
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/install/lib
